### ISSUE TITLE
漫画源制作请教

### ISSUE THREAD

**Issue by 11yiyang** [weilai199/xiangseComic#1]
您好，请问漫画源是您自己制作的吗？想请教一下翻页问题
网上看到规则说明“autoRequestMore(bool，success/more为true时生效，异步自动再请求)”
例如这个漫画网站，https://m.manhua39.com/update/  返回的数据more为false，maxPage为1，不能翻页再请求数据。
但是网页有翻页内容。请问这个是取决于我们写的规则还是app处理的逻辑。

**Comment by xsir99** [comment]
我也想问一下， 你们的书源是APP上制作的吗？ 然后再导出xbs文件？

**Comment by weilai199** [comment]
有些是自己制作的，有些是从其他地方拿的，就使用‘香色闺阁’制作的啊，看了别人的源，照着制作了一个，后来就熟悉了。

autoRequestMore我也没用过，我的理解是该参数仅在“使用js手动解析响应”时使用，如果xpath解析，不需要使用。
使用xpath规则时如果有多页地址，填写"下一页地址(nextPageUrl)"，然后在moreKeys中设置maxPage为2或更多，我觉得加maxPage的原因是防止循环请求吧。

**Comment by weilai199** [comment]
> 您好，请问漫画源是您自己制作的吗？想请教一下翻页问题
> 网上看到规则说明“autoRequestMore(bool，success/more为true时生效，异步自动再请求)”
> 例如这个漫画网站，https://m.manhua39.com/update/ 返回的数据more为false，maxPage为1，不能翻页再请求数据。
> 但是网页有翻页内容。请问这个是取决于我们写的规则还是app处理的逻辑。

见3楼

**Comment by weilai199** [comment]
> 您好，请问漫画源是您自己制作的吗？想请教一下翻页问题
> 网上看到规则说明“autoRequestMore(bool，success/more为true时生效，异步自动再请求)”
> 例如这个漫画网站，https://m.manhua39.com/update/ 返回的数据more为false，maxPage为1，不能翻页再请求数据。
> 但是网页有翻页内容。请问这个是取决于我们写的规则还是app处理的逻辑。

有些是自己制作的，有些是从其他地方拿的，就使用‘香色闺阁’制作的啊，看了别人的源，照着制作了一个，后来就熟悉了。

autoRequestMore我也没用过，我的理解是该参数仅在“使用js手动解析响应”时使用，如果xpath解析，不需要使用。
使用xpath规则时如果有多页地址，填写"下一页地址(nextPageUrl)"，然后在moreKeys中设置maxPage为2或更多，我觉得加maxPage的原因是防止循环请求吧。

**Comment by weilai199** [comment]
> 我也想问一下， 你们的书源是APP上制作的吗？ 然后再导出xbs文件？

好像只有App上制作书源吧，有其他更便捷的方式吗？

**Comment by 11yiyang** [comment]
> > 您好，请问漫画源是您自己制作的吗？想请教一下翻页问题
> > 网上看到规则说明“autoRequestMore(bool，success/more为true时生效，异步自动再请求)”
> > 例如这个漫画网站，https://m.manhua39.com/update/ 返回的数据more为false，maxPage为1，不能翻页再请求数据。
> > 但是网页有翻页内容。请问这个是取决于我们写的规则还是app处理的逻辑。
> 
> 有些是自己制作的，有些是从其他地方拿的，就使用‘香色闺阁’制作的啊，看了别人的源，照着制作了一个，后来就熟悉了。
> 
> autoRequestMore我也没用过，我的理解是该参数仅在“使用js手动解析响应”时使用，如果xpath解析，不需要使用。
> 使用xpath规则时如果有多页地址，填写"下一页地址(nextPageUrl)"，然后在moreKeys中设置maxPage为2或更多，我觉得加maxPage的原因是防止循环请求吧。

确实在js里解决了部分网站搜索及分类翻页问题。因为js里可以修改more的值为true。
